import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import {
  BookOpen,
  Copy,
  Download,
  RefreshCw,
  ArrowLeft,
  Check,
  Sparkles,
  Bookmark,
  Lightbulb,
  FileText,
  Key
} from 'lucide-react';
import api from '../services/api';
import { useToast } from '../context/ToastContext';
import Button from '../components/Button';
import Card from '../components/Card';
import { LoadingSpinner } from '../components/StateFeedback';

const AISummaryPage = () => {
  const { id } = useParams();
  const [summary, setSummary] = useState(null);
  const [doc, setDoc] = useState(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const { addToast } = useToast();
  const navigate = useNavigate();

  const fetchSummary = async () => {
    try {
      const docRes = await api.get(`/documents/${id}`);
      setDoc(docRes.data);
      if (docRes.data.summary) {
        setSummary(docRes.data.summary);
      } else {
        // Trigger auto summary generation
        const genRes = await api.post('/ai/summary', { document_id: Number(id) });
        setSummary(genRes.data);
      }
    } catch (err) {
      addToast(err.message || 'Failed to fetch summary', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, [id]);

  const handleRegenerate = async () => {
    try {
      setRegenerating(true);
      const res = await api.post('/ai/summary', { document_id: Number(id) });
      setSummary(res.data);
      addToast('Summary regenerated by AI!', 'success');
    } catch (err) {
      addToast(err.message || 'Failed to regenerate summary', 'error');
    } finally {
      setRegenerating(false);
    }
  };

  const handleCopy = () => {
    if (!summary) return;
    const textToCopy = `
# Summary: ${doc?.filename || 'Learning Material'}

## Overview
${summary.overview}

## Key Concepts
${summary.key_concepts?.map((c) => `- ${c}`).join('\n')}

## Important Definitions
${summary.definitions?.map((d) => `**${d.term}**: ${d.definition}`).join('\n')}

## Key Takeaways
${summary.key_takeaways?.map((t) => `- ${t}`).join('\n')}
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    addToast('Summary copied to clipboard!', 'success');
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    if (!summary) return;
    const textContent = `
# Summary: ${doc?.filename || 'Learning Material'}

## Overview
${summary.overview}

## Key Concepts
${summary.key_concepts?.map((c) => `- ${c}`).join('\n')}

## Important Definitions
${summary.definitions?.map((d) => `**${d.term}**: ${d.definition}`).join('\n')}

## Key Takeaways
${summary.key_takeaways?.map((t) => `- ${t}`).join('\n')}
    `.trim();

    const blob = new Blob([textContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${(doc?.filename || 'Summary').replace('.pdf', '')}_AI_Summary.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    addToast('Summary downloaded as Markdown file.', 'success');
  };

  if (loading) {
    return <LoadingSpinner fullPage text="Generating structured AI summary..." />;
  }

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fade-in pb-12">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate(doc ? `/materials/${doc.id}` : '/materials')}
            icon={ArrowLeft}
          >
            Back
          </Button>
          <div>
            <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white font-heading">
              AI Intelligent Summary
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              {doc?.filename || 'Document Summary'}
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            icon={copied ? Check : Copy}
          >
            {copied ? 'Copied' : 'Copy'}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownload}
            icon={Download}
          >
            Download
          </Button>
          <Button
            variant="primary"
            size="sm"
            onClick={handleRegenerate}
            isLoading={regenerating}
            icon={RefreshCw}
          >
            Regenerate
          </Button>
        </div>
      </div>

      {summary ? (
        <div className="space-y-6">
          {/* Section 1: Overview */}
          <Card className="p-6 sm:p-8 space-y-4" glass>
            <div className="flex items-center gap-2.5 text-primary-600 dark:text-primary-400 border-b border-slate-100 dark:border-darkBorder pb-3">
              <FileText className="w-5 h-5" />
              <h2 className="text-base font-bold text-slate-900 dark:text-white font-heading">
                Overview
              </h2>
            </div>
            <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              {summary.overview}
            </p>
          </Card>

          {/* Section 2: Key Concepts */}
          <Card className="p-6 sm:p-8 space-y-4" glass>
            <div className="flex items-center gap-2.5 text-secondary-600 dark:text-secondary-400 border-b border-slate-100 dark:border-darkBorder pb-3">
              <Lightbulb className="w-5 h-5" />
              <h2 className="text-base font-bold text-slate-900 dark:text-white font-heading">
                Key Concepts
              </h2>
            </div>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
              {summary.key_concepts?.map((concept, idx) => (
                <li
                  key={idx}
                  className="p-3.5 rounded-xl bg-slate-50 dark:bg-darkBg/60 border border-slate-100 dark:border-darkBorder flex items-start gap-3 text-xs text-slate-800 dark:text-slate-200"
                >
                  <span className="w-5 h-5 rounded-md bg-secondary-100 dark:bg-secondary-900/60 text-secondary-700 dark:text-secondary-300 font-bold flex items-center justify-center flex-shrink-0 text-[10px]">
                    {idx + 1}
                  </span>
                  <span className="leading-relaxed font-medium">{concept}</span>
                </li>
              ))}
            </ul>
          </Card>

          {/* Section 3: Important Definitions */}
          <Card className="p-6 sm:p-8 space-y-4" glass>
            <div className="flex items-center gap-2.5 text-cyanAccent-600 dark:text-cyanAccent-400 border-b border-slate-100 dark:border-darkBorder pb-3">
              <Key className="w-5 h-5" />
              <h2 className="text-base font-bold text-slate-900 dark:text-white font-heading">
                Important Definitions
              </h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              {summary.definitions?.map((def, idx) => (
                <div
                  key={idx}
                  className="p-4 rounded-xl bg-slate-50 dark:bg-darkBg/60 border border-slate-100 dark:border-darkBorder space-y-1.5"
                >
                  <span className="text-xs font-bold text-primary-600 dark:text-primary-400 block font-heading">
                    {def.term}
                  </span>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    {def.definition}
                  </p>
                </div>
              ))}
            </div>
          </Card>

          {/* Section 4: Key Takeaways */}
          <Card className="p-6 sm:p-8 space-y-4" glass>
            <div className="flex items-center gap-2.5 text-emerald-600 dark:text-emerald-400 border-b border-slate-100 dark:border-darkBorder pb-3">
              <Bookmark className="w-5 h-5" />
              <h2 className="text-base font-bold text-slate-900 dark:text-white font-heading">
                Key Takeaways & Best Practices
              </h2>
            </div>
            <div className="space-y-2.5 pt-1">
              {summary.key_takeaways?.map((takeaway, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200/60 dark:border-emerald-900/40 flex items-start gap-3 text-xs text-emerald-950 dark:text-emerald-200"
                >
                  <span className="text-emerald-600 dark:text-emerald-400 font-bold mt-0.5">✓</span>
                  <span className="leading-relaxed font-medium">{takeaway}</span>
                </div>
              ))}
            </div>
          </Card>
        </div>
      ) : (
        <p className="text-xs text-slate-400 text-center py-12">No summary available.</p>
      )}
    </div>
  );
};

export default AISummaryPage;
